### ISSUE TITLE
Article Proposal: JSON Schema bundling finally formalised

### ISSUE THREAD

**Issue by Relequestual** [OAI/Stories#11]
I've written an article covering the bnundling process for JSON Schema.

The idea for this article came about after a [discussion on twitter](https://twitter.com/relequestual/status/1364708002629001218) where I suggested the approach to merging external schemas had the potential to cause real problems.

While the article doesn't directly address the use case for code or form generation, it does present best practrice to form an ideal situation for standardised bundling of external JSON Schema resources into a single resource (or file). The bundling process results in a Compound JSON Schema Document, which is formally defined in JSON Schema draft 2020-12, and is also one of my largest direct contribution to the specification.

The article is already written and undergone a level of peer review.

@MikeRalphson has "topped and tailed" the article to provide a little context for OpenAPI readers.

My intent is to publish the article under a new soft launched JSON Schema blog, and if you're willing, cross post to the OpenAPI blog (and possibly a few others for increased visiblitly).

I'm not totally sure of the process here, but I'm ready to share a draft for review and feedback.
Please let me know how you'd like to proceed.

**Comment by kinlane** [comment]
I will bring up in the OAI marketing meeting and ask about 1) interest in the story, and 2) cross posting -- worse case on this is we'll have to write an OAI specific edition, which I am willing to help with.

**Comment by Relequestual** [comment]
Has there been a OAI marketing meeting since? Looking to publlish next week now, hopefully.

**Comment by kinlane** [comment]
Hey now. I only initially presented this to the OAI Marketing, and dropped ball as I was out of office. I can pick up this Friday, but it will take more time and editorial before it can be approved. What were your syndication strategy for this post? We can follow up in our Sync.

**Comment by Relequestual** [comment]
No problem. I'm planning to create a self coded (template repo based) self hosted (netlify) JSON Schema blog, and manually cross post to dev.to and hashnode. Possibly also to @philsturgeon API's you won't hate blog if he's still up for it.

I don't know if the OAI marketing group will then still want the cross posting to the OAI blog, but it's still possible and would be welcome =]

**Comment by philsturgeon** [comment]
Absolutely, I'd love a guest post on this for APIs You Won't Hate.

**Comment by kinlane** [comment]
@Relequestual -- Thumbs up from OAI marketing meeting to publish this to OAI blog, even if it is cross-posted to multiple locations. Is it ready for OAI editorial to look at?

**Comment by kinlane** [comment]
This was posted - https://www.openapis.org/blog/2021/08/23/json-schema-bundling-finally-formalised
